version: '3'

services:
  postgres:
    image: 'postgres:15.3'
    environment:
      - 'POSTGRES_USER=gamma'
      - 'POSTGRES_DB=gamma'
      - 'POSTGRES_PASSWORD=gamma'
    ports:
      - '5432:5432'
    networks:
      - gamma-network

  gamma:
    build: .
    depends_on:
      - postgres
    environment:
      - 'spring.datasource.url=jdbc:postgresql://postgres/gamma?user=gamma&password=gamma'
    ports:
      - '8080:8080'
    networks:
      - gamma-network

networks:
  gamma-network:
